services:
  app:                          # nom du service (choix libre)
    build:          # utiliser le dockerfile
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/var/www/html         # code source monté
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini #config xdebug

    networks:
      - laravel

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"               # port hôte:port conteneur
    volumes:
      - .:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app                     # démarre après app
    networks:
      - laravel

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql   # volume nommé pour persister les données
    networks:
      - laravel

volumes:
  mysql_data:                   # volume nommé déclaré ici

networks:
  laravel:                      # réseau interne entre les services
